spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        driverClassName: org.h2.Driver
jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
# https://www.appsdeveloperblog.com/document-spring-rest-api-with-openapi-3swagger/
# https://springdoc.org/#swagger-ui-configuration
# Specify the path of the OpenAPI documentation
springdoc:
    swagger-ui:
        defaultModelsExpandDepth: -1
        doc-expansion: none
jwt:
    secret: SequenciaDeCaracteresParaAssinarTokenSemWeakKeyException12345!@12345
    expiration: 300000000
